name: Byge CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  # Private go repository will be accessed
  GOPRIVATE: github.com/hkraftno/byge-common

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # remove this step if not using private go modules
      - name: Add SSH Go Module Private Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GO_MODULE_PRIVATE_KEY_BYGE_COMMON }}"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
      # remove this step if not using private go modules
      - name: Setup access for private go modules
        run: |
          git config --global url."ssh://git@github.com/".insteadOf https://github.com/

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
